POST http://localhost:4000/app/signup
Content-Type: application/json

{
    "firstName":"joseph",
    "lastName":"joey",
    "email":"joe@mail.com",
    "date":"2/2/2",
    "password":"12345",
    "storeChoice":"adsad",
    "optionalField":"1sfcef2" 
}

